CC = gcc

Pipe1 : Pipe1.c
		${CC} Pipe1.c -o Pipe1

Pipe2 : Pipe2.c
		${CC} Pipe2.c -o Pipe2

Pipe3 : Pipe3.c
		${CC} Pipe3.c -o Pipe3

Pipe4 : Pipe4.c
		${CC} Pipe4.c -o Pipe4
	
Pipe5 : Pipe5.c
		${CC} Pipe5.c -o Pipe5

Pipe6 : Pipe6.c
		${CC} Pipe6.c -o Pipe6


	